language: python
python:
  - 3.5
  - 3.6
  - 3.7-dev
cache: pip
before_install:
  - sudo apt-get update
  - sudo apt-get install -y yara
install:
  - pip install -r requirements.txt

script:
  - python fnord.py
  - python fnord.py -f ./test/launch-varplus.txt --noyara
  - ! cat fnord-rules.yar
  - python fnord.py -f ./test/vbs.txt --show-score --show-count
  - egrep -F "(1* 2^0 )" fnord-rules.yar -c
  - egrep "WScript" fnord-rules.yar -c
  - fnord.py -f ./test/inv-obf.txt --show-score --show-count -t 1 --yara-strings 4 --yara-exact
  - egrep -F "^'^2^+^2^" fnord-rules.yar -c
  - egrep -F "(^S^e^T ^ ^" fnord-rules.yar -c
  - egrep -F " ( ; ; ; (" fnord-rules.yar -c
  - python fnord.py -f ./test/wraeop.sct
  - egrep -F ",101," fnord-rules.yar -c
  - egrep -F "temp%/VRE" fnord-rules.yar -c

notifications:
  email:
    recipients:
      - venom14@gmail.com
    on_success: always
    on_failure: always
