language: python
python:
  - 3.5
  - 3.6
  - 3.7-dev
cache: pip
before_install:
  - sudo apt-get update
install:
  - pip install -r requirements.txt
  - mkdir temp
  - mkdir yara
  - set YARA_DIR="$PWD"/yara
  - wget -P ./temp https://github.com/VirusTotal/yara/archive/v3.6.3.tar.gz
  - tar -xvzf ./temp/v3.6.3.tar.gz -C ./temp/
  - cd ./temp/yara-3.6.3
  - ./bootstrap.sh
  - ./configure --disable-shared --disable-magic --disable-cuckoo --prefix=$YARA_DIR
  - make
  - cd ..
  - echo "$PWD"

script:
  - echo "$PWD"
  - ./yara/yara --version
  - python fnord.py
  - python fnord.py -f ./test/launch-varplus.txt --noyara
  - ! cat fnord-rules.yar
  - python fnord.py -f ./test/vbs.txt --show-score --show-count
  - fgrep "(1* 2^0 )" fnord-rules.yar -c
  - egrep "WScript" fnord-rules.yar -c
  - ./yara/yara -r fnord-rules.yar ./test
  - python fnord.py -f ./test/inv-obf.txt --show-score --show-count -t 1 --yara-strings 4 --yara-exact
  - fgrep "^'^2^+^2^" fnord-rules.yar -c
  - fgrep "(^S^e^T ^ ^" fnord-rules.yar -c
  - fgrep " ( ; ; ; (" fnord-rules.yar -c
  - yara -r fnord-rules.yar ./test
  - python fnord.py -f ./test/wraeop.sct
  - fgrep ",101," fnord-rules.yar -c
  - fgrep "temp%/VRE" fnord-rules.yar -c
  - ./yara/yara -r fnord-rules.yar ./test

notifications:
  email:
    recipients:
      - venom14@gmail.com
    on_success: always
    on_failure: always
